### PR TITLE
Fix SSR mismatch

### LINKED ISSUE #298: Pagination breaks SSR
Screenshot 2020-03-26 at 15 51 17

+ transition error

### PR DESCRIPTION
**Pull request by andrzejewsky**
closes: #298 
- [x] I Accept [Individual Contributor License Agreement](https://github.com/DivanteLtd/next/blob/master/CLA.md)

### CODE REVIEW

**Review by Qrzy — APPROVED** [review]

File: packages/core/factories/src/useProductFactory.ts [hunk 1]
```diff
@@ -19,16 +19,16 @@ export function useProductFactory<PRODUCT, PRODUCT_SEARCH_PARAMS>(
 ) {
   return function useProduct(cacheId: string): UseProduct<PRODUCT> {
     const { initialState, saveToInitialState } = useSSR(cacheId);
-    const products: Ref<PRODUCT[]> = ref(initialState || []);
-    const totalProducts = ref(0);
+    const products: Ref<PRODUCT[]> = ref(initialState ? initialState.data : []);
+    const totalProducts: Ref<number> = ref(initialState ? initialState.total : 0);
```
Comment (Qrzy) [inline packages/core/factories/src/useProductFactory.ts]: Just a little suggestion here :) 

```suggestion
    const products: Ref<PRODUCT[]> = ref(initialState?.data || []);
    const totalProducts: Ref<number> = ref(initialState?.total || 0);
```

**Review by filrak — APPROVED** [review]
