### PR TITLE
fix(commercetools): Refresh token flow

### LINKED ISSUE #351: Handle refreshing  token properly

### PR DESCRIPTION
**Pull request by andrzejewsky**
closes: https://github.com/DivanteLtd/next/issues/351
- [x] I'm confirming that if i made any changes to public APIs or exposed any public APIs they are doccumented.

### CODE REVIEW

File: packages/commercetools/api-client/__tests__/setup.ts [hunk 1]
```diff
@@ -7,7 +7,7 @@ jest.mock('apollo-client');
 jest.mock('@commercetools/sdk-auth', () => jest.fn(() => ({
   anonymousFlow: () => Promise.resolve('anonymous flow'),
   customerPasswordFlow: () => Promise.resolve('customer password flow'),
-  refreshTokenFlow: () => Promise.resolve('refresh token flow')
+  refreshTokenFlow: (refreshToken) => Promise.resolve(`refresh token flow ${refreshToken}`)
```
Comment (Qrzy) [inline packages/commercetools/api-client/__tests__/setup.ts]: Wouldn't it be enough just to resolve to `refreshToken`?

```suggestion
  refreshTokenFlow: (refreshToken) => Promise.resolve(refreshToken)
```

**Review by Qrzy — APPROVED** [review]
